name: lesgo

on:
  repository_dispatch:
    types: [cron-tick]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create scheduled test commit
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com"
          git commit --allow-empty -m "chore(repo): update source code and project files"
          git push
